anguage: java
jdk:
  - openjdk11
stages:
  - tests-sonar
  - deploy
  
jobs:
  include:
  - stage: tests-sonar
    addons:
      sonarcloud:
        organization: "savitoh"
        toke: 
            secure: "BxA2vxnrbWapibI09dY4UVkheILjm6mroSTL6TlbCyRSPDaOXRE+J5zAQrjmQuHb9JucYqdXHUBGV/T4ZE3KrgI8oqmGcJkWkscDQHifozY+RdiKtW4paoA/dMCa0o/dgKngA3aYf/nq6iYt0zw8ByNtaAgo8rSgid8jK/nKojJnHQOXs2jNEINxrewieqg4HxzhSdLfSk0q8X9FFoFxZiJ5j3DdHAc5AEJIcinT5lSW7dHF39X2o2inJllfnA0xiZ0h+5VglopXR4VQ+bXfF+JCpfIXBtQlF5DIaSqmxLGi6XCOYHCD+xKKF3eiHdUBHvirLkIiLJezUAH56FYoWrtRZzWtlpPSKZQGPIX6JoJGZgNXdDGGdgH0nEBwX/0YsO2meF479s9qXv2zcVvOmmVhXvA4JxSA8D/DpnvtVOmLxfOlagpGmho1M2nd/vamWu4DARUl4dCLuLHOuCrNRSjRsRcGcTPvUynWZ6xRsOAsyFe1CB39IelgGwlcM1Hcwg7oqR3V9u0OJ4Hy74R48GB7/HTxpKoLy2xfzL+CdUnGI4rdUBOuyliqFuGIbMgfQ8lwmVm3BHD7tW4gF2X6CUL0qJLs8N4MZDWPi0rVJsF0zdrtpGABGhecjLzcDGLScJ5bdUDHvMbdeXuUm4LXd9uWDHypxZlPgiGWrs7U1Mk="
    script:
      - mvn clean install sonar:sonar
  - stage: deploy
    script: echo "Deploying... (noop)"
    
notifications:
  email: true