anguage: java
jdk:
  - openjdk11
stages:
  - tests-sonar
  - deploy
  
jobs:
  include:
  - stage: tests-sonar
    addons:
      sonarcloud:
        organization: "savitoh"
        toke: 
            secure: "bLfTzllFt9ElfODB2eqdiCne6MVvTvhKMdesH1uB5yiBxADtrzcDlg50U5SSK+edQRZap75fkBK/UHiGZ6UxzaecNYUXZU0mHYBJdgeCZM4bgQLkdEVLvUIpL53gJxnAUa4KA1YrQEKzgEKser3cH01Vb4SRlwYQt/+2gRA/yvV0HtPArajnKGBCP80OoHWZYJYwqk+T/5Hna1Mm3d73bZPxPWQsxez9+QAOdZFBSo3QOlgiIw+HMknUud24L9AJ80BbVg32tt2huvZqANvkJP+rjp7MrRd446R5QJnFoMJ+se9st5SfMLdTOZbqDsZBvqThSeox/oF8x69Yr1EigUSsTkxKJ61b8zoxWwL48tMLDYkyfk48pT2sQFzj17vVuNqWGmu5cXpFSrEKPBitm+1DyBvupAw1MFYpeVQ6vkKzKW1PoTnswT1sSS4f6FdPcpbgaFVomV6RCVvVAIQC85Y81DLfhFq94pxaJivm/ZFp3dp23M9ZdCLpjqKTNK8skulFKqIEY7KMTlZu8lFaNqvJ9dRMCT5k+jI8ftapPC0Tq8hbNEomjdZCxk50rtF2uk/BVc/a1sPjCa9Irxe56BzZNsyXY/g5/3znk9FT+U2cF7AcmM3f4pbttacsGetWIiW8OSTH5Y+EP7iiVfx4YqZMzGNvdv1lkAlj9X0xV7U="
    script:
      - mvn clean install sonar:sonar
  - stage: deploy
    script: echo "Deploying... (noop)"
    
notifications:
  email: true