anguage: java
jdk:
  - openjdk11
stages:
  - tests-sonar
  - deploy
  
jobs:
  include:
  - stage: tests-sonar
    addons:
      sonarcloud:
        organization: "savitoh"
        toke: 
            secure: "EGyM4PHADEw9E7IJgnUzIroIEriIWmIL1Zu54S2CEpoNy0Jlf6MqP00VRtzH/IWBIFsoIUB3IvIJJqeP1PkA8J5kMt0fXLbeSZWZSL7tQqMIlYniQKjxMbFEcQA5rbUrHwaEvO49ll7uKWetSZG1kxc7STeqjDvBD507NiANz5Tl+w95lPMDyH4p/nmp70CAv96VOcA1Y1Cf0Kcas/bw145ybCzox4dvnkdrdrVwCSEBdsLbngeJfkX7q6hXuHlo9VkLgp9hlge4WCQxiAMRXLzDI7GXA6XJj5UrV5yWzjWV0ci/vWobNEkXLVo/MjrZsjDLge2d3bCCJHwogzJSCVq5JNWTpo/WY5PlEQzD1mn4m4N8C15Ta2I7iOFWB/g3371fwWOHDtWB24QKgW0+H7ZyXvp24p75zjiHY1hTtPkJ23hypUkGCja+fGh5HeW1c+oP3indVSp4M3Vv99oFc8aEp3lswR6KZ+/wt6WQ3arpQ762TR03mJzm1lmLjqARykrc8nSyM9UpUPe40G4mUixYX4ridlitxn7knEk8RiyqgYxd/kW/isNscVTYAIxasu+tJEifwPGhyVW1Qz0rhkjcIBJ0PN7+mlLvSHok+HHg0p+MpZuWKYyG8HXgheX0xR4xv2KCyT6sqGLqvi72qlRhYyUud9BQBrcXGi7V44c="
    script:
      - mvn clean install sonar:sonar
  - stage: deploy
    script: echo "Deploying... (noop)"
    
notifications:
  email: true